export const SEARCH_LOADING = 'SEARCH_LOADING';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const ITEM_DETAIL_LOADING = 'ITEM_DETAIL_LOADING';
export const ITEM_DETAIL_SUCCESS = 'ITEM_DETAIL_SUCCESS';
export const ITEM_DETAIL_ERROR = 'ITEM_DETAIL_ERROR';
